"""Reasoning Protocol — forces the agent to think before it acts.

This is the core change that turns Hermes-Omni from a "tool-dispatch loop"
into a "reasoning-first agent". The protocol has four phases:

    ┌─────────┐     ┌──────────┐     ┌─────────┐     ┌──────────┐
    │  PLAN   │ ──▶ │ CRITIQUE │ ──▶ │ EXECUTE │ ──▶ │ REFLECT  │
    └─────────┘     └──────────┘     └─────────┘     └──────────┘

Design goals
------------
1. **Don't bottleneck the LLM.** Plans are generated by the LLM itself,
   through a single function call. No multi-turn scaffolding, no chained
   prompts. One call, one plan.
2. **Match plan depth to action consequence.** A `read_file` is TRIVIAL —
   skip planning entirely. A `git push --force` is IRREVERSIBLE — generate
   a full plan AND a critique AND require explicit acknowledgement.
3. **Never block — escalate.** The protocol does not refuse actions. It
   returns structured reasoning that the conversation loop can choose to
   present to the user, log, or proceed. The LLM is the judge, not the
   framework.
4. **Fail open, not closed.** If the LLM call fails (network, quota, etc.),
   the protocol degrades to the legacy path: execute the tool. Better to
   execute one risky action than to brick the agent entirely.

Why not just rely on the LLM's chain-of-thought?
------------------------------------------------
Top-tier LLMs (Claude Opus, GPT-5, GLM-4.6, DeepSeek R1) already reason
well internally. But:

- Not all models do. The framework should support any model the user picks.
- Internal CoT is invisible to the framework, so the framework cannot
  learn from it, recall it, or surface it to the user.
- The protocol gives the framework a *structured* reasoning artifact that
  can be persisted, recalled, and audited. This is what makes the agent
  self-improving across sessions.

The protocol is therefore NOT a replacement for the LLM's own reasoning —
it's a structured surface that *captures* that reasoning for downstream
use (reflexion, recall, user display, audit log).
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from typing import Any, Literal

from .decision import Classification, DecisionClass, DecisionFramework


# --------------------------------------------------------------------------- #
# Data structures
# --------------------------------------------------------------------------- #


@dataclass
class ReasoningPlan:
    """Structured plan generated before an action."""

    tool_name: str
    args_summary: str
    goal: str
    approach: str
    alternatives: str
    risks: str
    reversibility: str
    decision: Literal["proceed", "abort", "ask_user"]
    rationale: str
    classification: str
    created_at: float = field(default_factory=time.time)
    elapsed_ms: int = 0

    def as_prompt_block(self) -> str:
        """Render as a markdown block suitable for inclusion in conversation."""
        lines = [
            "<reasoning-plan>",
            f"tool: {self.tool_name}",
            f"classification: {self.classification}",
            f"goal: {self.goal}",
            f"approach: {self.approach}",
        ]
        if self.alternatives:
            lines.append(f"alternatives: {self.alternatives}")
        if self.risks:
            lines.append(f"risks: {self.risks}")
        if self.reversibility:
            lines.append(f"reversibility: {self.reversibility}")
        lines.append(f"decision: {self.decision}")
        if self.rationale:
            lines.append(f"rationale: {self.rationale}")
        lines.append("</reasoning-plan>")
        return "\n".join(lines)


@dataclass
class ReasoningCritique:
    """Self-critique of a plan. Only generated for CONSEQUENTIAL+ actions."""

    blind_spots: str
    assumptions_verified: str
    assumptions_invalid: str
    recommendation: Literal["proceed", "modify", "abort"]
    modified_approach: str = ""
    created_at: float = field(default_factory=time.time)
    elapsed_ms: int = 0


@dataclass
class ReasoningReflection:
    """Post-action reflection. Persisted into the reflexion store."""

    tool_name: str
    outcome_matched: bool
    expected: str
    actual: str
    lesson: str
    score: float = 1.0  # higher = more valuable lesson
    created_at: float = field(default_factory=time.time)


# --------------------------------------------------------------------------- #
# Plan generation prompts
# --------------------------------------------------------------------------- #

_PLAN_SYSTEM_PROMPT = (
    "You are the reasoning layer of an AI agent. Your job is to produce a "
    "structured plan before the agent executes a tool. Be concise, honest, "
    "and specific. Do not pad. If the action is safe, say so briefly. If "
    "the action is risky, articulate the risk precisely.\n\n"
    "Return STRICT JSON only — no prose, no markdown fences. Schema:\n"
    "{\n"
    '  "goal": "what this action is supposed to achieve",\n'
    '  "approach": "how this tool call achieves the goal",\n'
    '  "alternatives": "other viable approaches, or empty string if none",\n'
    '  "risks": "what could go wrong, or empty string if nothing notable",\n'
    '  "reversibility": "can this be undone? how?",\n'
    '  "decision": "proceed" | "abort" | "ask_user",\n'
    '  "rationale": "one-sentence justification for the decision"\n'
    "}"
)

_CRITIQUE_SYSTEM_PROMPT = (
    "You are the self-critique layer of an AI agent. You are given a plan "
    "for a consequential or irreversible action. Your job is to find blind "
    "spots, verify or invalidate assumptions, and recommend whether to "
    "proceed. Be skeptical but not paranoid.\n\n"
    "Return STRICT JSON only. Schema:\n"
    "{\n"
    '  "blind_spots": "what the plan missed",\n'
    '  "assumptions_verified": "assumptions the plan made that are correct",\n'
    '  "assumptions_invalid": "assumptions the plan made that are wrong, or empty",\n'
    '  "recommendation": "proceed" | "modify" | "abort",\n'
    '  "modified_approach": "if recommendation=modify, describe the change"\n'
    "}"
)

_REFLECT_SYSTEM_PROMPT = (
    "You are the reflection layer of an AI agent. Compare the expected "
    "outcome of a tool call to the actual outcome, and extract a lesson "
    "that will be useful for future similar situations. Be specific — "
    "generic lessons like 'be careful' are useless.\n\n"
    "Return STRICT JSON only. Schema:\n"
    "{\n"
    '  "outcome_matched": true | false,\n'
    '  "expected": "what the plan expected",\n'
    '  "actual": "what actually happened (brief)",\n'
    '  "lesson": "the transferable lesson, or empty if nothing notable",\n'
    '  "score": 0.0 to 5.0 — how valuable is this lesson for future use?\n'
    "}"
)


# --------------------------------------------------------------------------- #
# Plan argument formatting
# --------------------------------------------------------------------------- #


def _summarize_args(args: dict[str, Any] | None, *, max_chars: int = 800) -> str:
    if not args:
        return "(no arguments)"
    try:
        text = json.dumps(args, ensure_ascii=False, default=str)
    except Exception:
        text = str(args)
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + f"…<truncated, {len(text) - max_chars} more chars>"


def _build_plan_user_prompt(
    *,
    tool_name: str,
    args: dict[str, Any] | None,
    classification: Classification,
    conversation_context: str,
) -> str:
    return (
        f"Tool: {tool_name}\n"
        f"Classification: {classification.cls.name} — {classification.reason}\n"
        f"Arguments: {_summarize_args(args)}\n\n"
        f"Conversation context (brief):\n{conversation_context}\n\n"
        "Produce the plan JSON now."
    )


def _build_critique_user_prompt(plan: ReasoningPlan, classification: Classification) -> str:
    return (
        f"Action classification: {classification.cls.name}\n"
        f"Matched signal: {classification.reason}\n\n"
        f"Plan to critique:\n{plan.as_prompt_block()}\n\n"
        "Produce the critique JSON now."
    )


def _build_reflect_user_prompt(
    *,
    plan: ReasoningPlan,
    tool_name: str,
    args: dict[str, Any] | None,
    result_preview: str,
    duration_ms: int,
) -> str:
    return (
        f"Plan that was made before the action:\n{plan.as_prompt_block()}\n\n"
        f"Tool executed: {tool_name}\n"
        f"Arguments: {_summarize_args(args)}\n"
        f"Duration: {duration_ms} ms\n\n"
        f"Actual result (truncated):\n{result_preview}\n\n"
        "Produce the reflection JSON now."
    )


# --------------------------------------------------------------------------- #
# The protocol
# --------------------------------------------------------------------------- #


class ReasoningProtocol:
    """ Orchestrates plan → critique → execute → reflect.

    The protocol is intentionally stateless across tool calls: each call to
    `plan()`, `critique()`, `reflect()` is independent. The conversation
    loop is responsible for stitching them together. This keeps the
    protocol testable and side-effect free.

    The protocol needs an LLM client to generate plans/critiques/reflections.
    It accepts a `llm_call` callable that takes (system_prompt, user_prompt)
    and returns a string. The framework supplies this; if none is supplied,
    the protocol degrades to "no-plan mode" (executes without reasoning)
    and logs a warning.
    """

    def __init__(
        self,
        *,
        llm_call=None,
        decision_framework: DecisionFramework | None = None,
        conversation_context_provider=None,
    ) -> None:
        self._llm_call = llm_call
        self._decider = decision_framework or DecisionFramework()
        # conversation_context_provider() -> str (last N turns, summarized)
        self._context_provider = conversation_context_provider or (lambda: "")

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def classify(self, tool_name: str, args: dict[str, Any] | None) -> Classification:
        """Cheap pre-flight: how much reasoning does this action need?"""
        return self._decider.classify(tool_name, args)

    def plan(
        self,
        *,
        tool_name: str,
        args: dict[str, Any] | None,
        classification: Classification,
    ) -> ReasoningPlan | None:
        """Generate a structured plan. Returns None if LLM is unavailable
        or classification is TRIVIAL (skip planning entirely)."""
        if classification.is_trivial:
            return None
        if self._llm_call is None:
            return None
        try:
            user_prompt = _build_plan_user_prompt(
                tool_name=tool_name,
                args=args,
                classification=classification,
                conversation_context=self._context_provider(),
            )
            started = time.time()
            raw = self._llm_call(_PLAN_SYSTEM_PROMPT, user_prompt)
            elapsed = int((time.time() - started) * 1000)
            data = self._parse_json(raw)
            if data is None:
                return None
            return ReasoningPlan(
                tool_name=tool_name,
                args_summary=_summarize_args(args),
                goal=str(data.get("goal", "")).strip(),
                approach=str(data.get("approach", "")).strip(),
                alternatives=str(data.get("alternatives", "")).strip(),
                risks=str(data.get("risks", "")).strip(),
                reversibility=str(data.get("reversibility", "")).strip(),
                decision=str(data.get("decision", "proceed")).strip() or "proceed",
                rationale=str(data.get("rationale", "")).strip(),
                classification=classification.cls.name,
                elapsed_ms=elapsed,
            )
        except Exception:
            # Fail open: no plan → execute anyway. The conversation loop
            # will see plan=None and proceed without reasoning overhead.
            return None

    def critique(
        self,
        *,
        plan: ReasoningPlan,
        classification: Classification,
    ) -> ReasoningCritique | None:
        """Self-critique the plan. Only called for CONSEQUENTIAL+ actions."""
        if not classification.requires_critique:
            return None
        if self._llm_call is None:
            return None
        try:
            user_prompt = _build_critique_user_prompt(plan, classification)
            started = time.time()
            raw = self._llm_call(_CRITIQUE_SYSTEM_PROMPT, user_prompt)
            elapsed = int((time.time() - started) * 1000)
            data = self._parse_json(raw)
            if data is None:
                return None
            return ReasoningCritique(
                blind_spots=str(data.get("blind_spots", "")).strip(),
                assumptions_verified=str(data.get("assumptions_verified", "")).strip(),
                assumptions_invalid=str(data.get("assumptions_invalid", "")).strip(),
                recommendation=str(data.get("recommendation", "proceed")).strip() or "proceed",
                modified_approach=str(data.get("modified_approach", "")).strip(),
                elapsed_ms=elapsed,
            )
        except Exception:
            return None

    def reflect(
        self,
        *,
        plan: ReasoningPlan | None,
        tool_name: str,
        args: dict[str, Any] | None,
        result: Any,
        duration_ms: int = 0,
    ) -> ReasoningReflection | None:
        """Post-action reflection. Returns None if no plan was made or LLM unavailable."""
        if plan is None or self._llm_call is None:
            return None
        try:
            result_preview = self._preview(result)
            user_prompt = _build_reflect_user_prompt(
                plan=plan,
                tool_name=tool_name,
                args=args,
                result_preview=result_preview,
                duration_ms=duration_ms,
            )
            started = time.time()
            raw = self._llm_call(_REFLECT_SYSTEM_PROMPT, user_prompt)
            elapsed = int((time.time() - started) * 1000)
            data = self._parse_json(raw)
            if data is None:
                return None
            try:
                score = float(data.get("score", 1.0))
            except (TypeError, ValueError):
                score = 1.0
            return ReasoningReflection(
                tool_name=tool_name,
                outcome_matched=bool(data.get("outcome_matched", False)),
                expected=str(data.get("expected", "")).strip(),
                actual=str(data.get("actual", "")).strip(),
                lesson=str(data.get("lesson", "")).strip(),
                score=max(0.0, min(5.0, score)),
                created_at=time.time(),
            )
        except Exception:
            return None

    # ------------------------------------------------------------------ #
    # Batch reflection (for background worker)
    # ------------------------------------------------------------------ #

    _REFLECT_BATCH_SYSTEM_PROMPT = (
        "You are the reflection layer of an AI agent. You will receive a "
        "batch of N completed tool calls. For each, compare the expected "
        "outcome to the actual outcome, and extract a transferable lesson. "
        "Be specific — generic lessons like 'be careful' are useless. If "
        "an item has nothing notable, return an empty lesson for it.\n\n"
        "Return STRICT JSON: an array of N objects, in the same order as "
        "the input. Schema per object:\n"
        "{\n"
        '  "outcome_matched": true | false,\n'
        '  "expected": "what the plan expected",\n'
        '  "actual": "what actually happened (brief)",\n'
        '  "lesson": "the transferable lesson, or empty if nothing notable",\n'
        '  "score": 0.0 to 5.0\n'
        "}"
    )

    def reflect_batch(
        self,
        items: list[dict[str, Any]],
    ) -> list[dict[str, Any] | None]:
        """Reflect on a batch of completed tool calls in one LLM call.

        Used by the background reflection worker (longrun.py). Each item
        in `items` is a dict with: plan, tool_name, args, result,
        duration_ms, session_id, turn_id, scope.

        Returns a list of the same length as `items`, where each entry
        is either None (reflection failed) or a dict with keys:
        outcome_matched, expected, actual, lesson, score.
        """
        n = len(items)
        if n == 0 or self._llm_call is None:
            return [None] * n

        # Build a single prompt with all items.
        parts = [f"Batch of {n} tool calls to reflect on:\n"]
        for i, item in enumerate(items, 1):
            plan = item.get("plan")
            plan_block = (
                plan.as_prompt_block()
                if hasattr(plan, "as_prompt_block")
                else f"(plan: {str(item.get('plan_summary', ''))[:200]})"
            )
            result_preview = self._preview(item.get("result"), max_chars=600)
            parts.append(
                f"\n--- Item {i} ---\n"
                f"Tool: {item.get('tool_name', '?')}\n"
                f"Duration: {item.get('duration_ms', 0)} ms\n"
                f"Plan:\n{plan_block}\n"
                f"Result (truncated):\n{result_preview}\n"
            )
        user_prompt = "\n".join(parts) + "\n\nReturn the JSON array now."

        try:
            raw = self._llm_call(self._REFLECT_BATCH_SYSTEM_PROMPT, user_prompt)
            data = self._parse_json_array(raw)
            if data is None or len(data) != n:
                # Length mismatch — can't reliably associate. Drop all.
                return [None] * n
            results: list[dict[str, Any] | None] = []
            for entry in data:
                if not isinstance(entry, dict):
                    results.append(None)
                    continue
                try:
                    score = float(entry.get("score", 1.0))
                except (TypeError, ValueError):
                    score = 1.0
                results.append(
                    {
                        "outcome_matched": bool(entry.get("outcome_matched", False)),
                        "expected": str(entry.get("expected", "")).strip(),
                        "actual": str(entry.get("actual", "")).strip(),
                        "lesson": str(entry.get("lesson", "")).strip(),
                        "score": max(0.0, min(5.0, score)),
                    }
                )
            return results
        except Exception:
            return [None] * n

    @staticmethod
    def _parse_json_array(raw: str) -> list[dict[str, Any]] | None:
        if not raw:
            return None
        text = raw.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            text = "\n".join(lines).strip()
        try:
            data = json.loads(text)
            if isinstance(data, list):
                return data
        except Exception:
            pass
        # Fallback: extract [ ... ] block.
        start = text.find("[")
        end = text.rfind("]")
        if start >= 0 and end > start:
            try:
                data = json.loads(text[start : end + 1])
                if isinstance(data, list):
                    return data
            except Exception:
                return None
        return None

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _preview(value: Any, *, max_chars: int = 1500) -> str:
        if value is None:
            return "(no result)"
        if isinstance(value, str):
            text = value
        else:
            try:
                text = json.dumps(value, ensure_ascii=False, default=str)
            except Exception:
                text = str(value)
        if len(text) <= max_chars:
            return text
        return text[:max_chars] + f"…<truncated, {len(text) - max_chars} more chars>"

    @staticmethod
    def _parse_json(raw: str) -> dict[str, Any] | None:
        if not raw:
            return None
        # Strip markdown fences if the model added them despite instructions.
        text = raw.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            text = "\n".join(lines).strip()
        # Try direct parse first.
        try:
            return json.loads(text)
        except Exception:
            pass
        # Fallback: extract the largest {...} block.
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            try:
                return json.loads(text[start : end + 1])
            except Exception:
                return None
        return None


# --------------------------------------------------------------------------- #
# Module-level singleton
# --------------------------------------------------------------------------- #

_protocol: ReasoningProtocol | None = None


def get_protocol() -> ReasoningProtocol:
    global _protocol
    if _protocol is None:
        _protocol = ReasoningProtocol()
    return _protocol


def configure_protocol(
    *,
    llm_call=None,
    decision_framework: DecisionFramework | None = None,
    conversation_context_provider=None,
) -> ReasoningProtocol:
    """Replace the global protocol with a configured one.

    Called by Hermes' setup path once the LLM client is available, so that
    subsequent tool calls can use real reasoning instead of the no-LLM
    fallback.
    """
    global _protocol
    _protocol = ReasoningProtocol(
        llm_call=llm_call,
        decision_framework=decision_framework,
        conversation_context_provider=conversation_context_provider,
    )
    return _protocol
